# Generated by Django 5.1.3 on 2024-11-14 22:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_id', models.CharField(max_length=255)),
                ('input_amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('input_currency', models.CharField(max_length=3)),
                ('output_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('output_currency', models.CharField(max_length=3)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
